services:
  db:
    image: pgvector/pgvector:pg16
    container_name: pg-lab
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lab
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    shm_size: "1gb"

volumes:
  pgdata: